import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'lib/core/index.ts',
    'constants/index': 'lib/core/constants/index.ts',
    'utils/index': 'lib/core/utils/index.ts',
    'ddd/index': 'lib/ddd/index.ts',
    'database/index': 'lib/database/index.ts',
    'messaging/index': 'lib/messaging/index.ts',
    'errors/index': 'lib/errors/index.ts',
    'openapi/index': 'lib/openapi/index.ts',
    'response/index': 'lib/response/index.ts',
    'types/index': 'lib/types/index.ts',
    'validator/index': 'lib/validator/index.ts',
    'authz/index': 'lib/authz/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    '@nestjs/common',
    '@nestjs/core',
    '@nestjs/event-emitter',
    '@nestjs/swagger',
    '@nestjs/typeorm',
    'typeorm',
    'zod',
    'rxjs',
    'reflect-metadata',
    'nest-commander',
  ],
  treeshake: true,
  minify: false,
});
